### ISSUE TITLE
Connect and Login logic should change for new orchestrator.

### ISSUE THREAD

**Issue by cwidisgroup** [cwi-dis/VR2Gather#136]
Login is now no longer optional.

**Comment by jackjansen** [comment]
The real problem is that there's part of the business logic in `OrchestratorLogin` and part in `OrchstratorController`.

This should all go to `OrchestratorController`, with `OrchestratorLogin` being just the UI.

And `OrchestratorController` also contains some bits and pieces that have to do with the current orchestrator implementation (using SocketIO), which should really move down into a lower-level class.
