### ISSUE TITLE
Support for WebRTC should be provided for the newest version of the orchestrator

### ISSUE THREAD

**Issue by jvdrhoof** [cwi-dis/VR2Gather#161]

**Comment by jackjansen** [comment]
@jvdrhoof I see that you've updated the new 161 branch to the last state of the `master` branch just before VR2Gather became a unity package. I.e. to the branch that is nowadays known as `historic/framework`.

I think it is a good idea to also do the next jump: to the unity package (i.e. to what is currently `master`). Because the longer we delay this the harder it will become. Mainly because every file in the repo has moved to a different location, and merging changes in the same file in different locations I have found to be rather gruesome (i.e. often git gets confused, in my experience).

I'll try to see whether I can get your current 161 branch running all by myself, then I can after that do the merge of the new master. Otherwise maybe we can find some time next week to do it together.

**Comment by jackjansen** [comment]
I had a quick look at the 161 branch.

I think it's best if I first implement #164 before I try merging the current `master` into 161, because this will mean that all the "webrtc-specific" code will be in the package. If I try merging now it would mean that part of the code, the `LoginManager.unity` changes, would be in the Samples copied into the VRTApp. That's bound to cause headaches later.
