### ISSUE TITLE
Replace BestHTTP by an open source socketIO implementation

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#169]
We need to get rid of BestHTTP, because it is not open source.

This depends on #168 because otherwise we would lose our default live media transport mechanism.

**Comment by troeggla** [comment]
Implementation is complete and works mostly, but there are disconnects when packets are sent out of order (I think).

Playing around in the application, I gathered the following information:
- If i connect and just move around, the connection will never break
- If i press one of the buttons in the scene, the connection is terminated sometimes
- If i spam said button, the connection always breaks after a few presses

Using Wireshark to log the packets the following exchange happens normally:
- The client sends a *WebSocket Text* packet containing the scene event itself, i.e. `SceneEventToAllUsers` with the key `SceneEventFrom` identifying the sender
- Following this, it sends a *WebSocket Binary* packet containing the scene event data itself

In the error condition, this happens:
- Client sends a *WebSocket Text* packet
- Client immediately sends another *WebSocket Text* packet
- Client sends a *WebSocket Binary* packet, which Wireshark either cannot decode or just contains garbage
- Server issues a *WebSocket Close* packet
- Client acknowledges with its own *WebSocket Close*

So i think the server expects a binary packet after a text packet but doesn't get one and closes the connection because it thinks the client is misbehaving. I will try to place all outgoing packets in a send queue and see if that makes any difference

**Comment by troeggla** [comment]
The final binary packet actually does contain the `byte[]` for both events, yet somehow the server seems to not accept this

**Comment by troeggla** [comment]
So, I found a fork of `SocketIOUnity` with uses a newer version of `socket.io-client-csharp` and that has fixed the issue. Everything works as intended, even SocketIO transport.

Find the latest version in my forked repository: https://github.com/troeggla/VR2Gather

All the BestHTTP stuff still needs to be cleaned out, but I'm going to do that tomorrow!
