### ISSUE TITLE
Ensure VR2Gather can be built and tested from a source distribution zipfile

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#170]
We should ensure that if you get a source zipfile of VR2Gather it can be built and it can be tested.

The main issue here is that the instructions are clear enough, I guess. 

Assigning to @troeggla because if I do it then I will probably automatically do the right things, without noticing that the instructions are actually missing.

**Comment by ireneviola** [comment]
Can we get latency numbers etc (similar to the IEEEMM paper) for this new implementation?

**Comment by troeggla** [comment]
Orchestrator:
- Downloaded ZIP from Github
- Installed Docker
- Extracted archive
- Ran `docker compose up` as per README
- Orchestrator builds and boots without issue

VR2Gather:
- Downloaded ZIP from Github including LFS assets
- Extracted it and opened one of the sample applications in Unity Hub
- Installed editor as prompted
- Opened VRTLogin scene from scenes folder
- Changed orchestrator URL in VRTInitializer object to `localhost` (this is optional, but since we're submitting the orchestrator as well, maybe we can make that default, to be discussed)
- Pressed play, application runs as expected and connects to the orchestrator, scene events work

These tests were performed on Scallion. I'm closing this issue now. Will write detailed instructions on the weekend.
