### ISSUE TITLE
Fix remaining mediascape issues

### ISSUE THREAD

**Issue by cwidisgroup** [cwi-dis/VR2Gather#86]
This issue keeps track of things that remain to be fixed in mediascape.
Let's check the boxes as they are fixed, and open new issues if things are more complex.

- [x] The piano doesn't play.
- [x] One of the drumsticks doesn't stick to your hand.
- [x] Not all guitars are grabbable correctly.
- [x] The sheet music and albums (on the piano) can't be picked up.
- [x] The camera (and photographs) aren't based on the mudball generator
- [x] #85 
- [x] #87
- [x] Fix "teleportability" of various floor segments. Unsure whether this is best done by an overlay floor or by fixing the individual floor segments.

**Comment by cwidisgroup** [comment]
As of [a1a1cba], scene switching has stopped working, we cannot get to the stage from the museum. Both the "why not" button and the "go" button (on screen5 of the information panel) have stopped working. The "let's go" seems to be working correctly

**Comment by cwidisgroup** [comment]
We're getting a warning saying there are two event systems in the scene, havent noticed this before

**Comment by cwidisgroup** [comment]
Testing [a1a1cba], both direct and ray based interaction (grab and point) work but we can no longer interact with the heads up display

**Comment by jackjansen** [comment]
Costume size (or actually user size) should still be communicated to the other participants.

**Comment by jackjansen** [comment]
It's not only costume size (I think) but also "skeleton" positions and head position.

At the moment (October 2023) if you go to the stage with two participants both will see themselves somewhat reasonable (slight head offset), but the other participant much less natural (bigger head offset, joints bending the wrong way because something is wrong with size).

Maybe we should first investigate on `master`, with the simple animated Marie-antoinette.
